name: CI

on:
  pull_request: # Run on pull requests

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Build extension
        run: ./gradlew bwextension

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: WigAI.bwextension-pr-${{ github.event.number || github.sha }}
          path: build/extensions/WigAI.bwextension
          retention-days: 7
